## DB Connection ##
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://navi.cju1qn1vahyl.ap-northeast-2.rds.amazonaws.com:3306/navi?serverTimezone=UTC&characterEncoding=UTF-8
    username: maserati_admin
    password: msa0516#$
    
    
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    # hibernate:
      #format_sql: true
      #ddl-auto: update
      #show-sql : true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE  




# pring.datasource.continue-on-error=true